#!/bin/sh

TASK="tcpsvd"
CMD="$TASK -E 0.0.0.0 21 ftpd -w /root "

case "$1" in
	status)
		if pidof $TASK | sed "s/$$\$//" | grep -q [0-9] ; then
			echo "running"
		else
			echo "stopped"
		fi
		;;

	start) 
		if ! pidof $TASK | sed "s/$$\$//" | grep -q [0-9] ; then
			$CMD 2> /dev/null &
		fi	
		;;

	stop) 
		pkill $TASK 2> /dev/null &
		;;

	restart)
		"$0"	stop
		"$0"	start
		;;

	*)
		echo $"Usage: $0 {start|stop|restart}"
		exit 1
esac
