#!/bin/sh

case "$1" in
    start)
		;;
	stop)
		;;
	restart)
		;;
	status)
		if pidof pppd | sed "s/$$\$//" | grep -q [0-9] ; then
			if pidof pppd >/dev/null ; then
				echo "running"
			else
				echo "stopped"
			fi
		else
			echo "stopped"
		fi
		;;
esac        

