#!/bin/sh

case "$1" in
	start) 
		if ! pidof httpd | sed "s/$$\$//" | grep -q [0-9]
		then
			/usr/sbin/httpd -h /www 2> /dev/null
		fi	
		;;

	stop) 
		pkill httpd 2> /dev/null
		;;

	restart)
		"$0"	stop
		"$0"	start
		;;

	status)
		if pidof httpd | sed "s/$$\$//" | grep -q [0-9]
		then
			echo "running"
		else
			echo "stopped"
		fi
		;;

	*)
		echo $"Usage: $0 {start|stop|restart|status}"
		exit 1
esac
