#!/bin/sh

case "$1" in
    start)
		if ! pidof syslogd | sed "s/$$\$//" | grep -q [0-9]
		then
			if [ -e /etc/service/syslogd ]
			then
				USED=`cat /etc/service/syslogd`
				if [ $USED = 'enabled' ]
				then
					syslogd 
					klogd -c 1
				fi
			fi
		fi
		;;

	stop)
	    pkill klogd 2>/dev/null
		pkill syslogd 2>/dev/null
		;;


	restart)
		"$0"	stop
		"$0"	start
		;;

	status)
		if pidof syslogd | sed "s/$$\$//" | grep -q [0-9] ; then
			if pidof klogd >/dev/null ; then
				echo "running"
			else
				echo "stopped"
			fi
		else
			echo "stopped"
		fi
		;;

	*)
		echo $"Usage: $0 {start|stop|restart|status}"
		exit 1
esac        

