#!/bin/sh

case "$1" in
	start) 
		if ! pidof vsftpd | sed "s/$$\$//" | grep -q [0-9]
		then
			if [ -e /etc/service/vsftpd ]
			then
				USED=`cat /etc/service/vsftpd`
				if [ $USED = 'enabled' ]
				then
					vsftpd &
				fi
			fi
		else
			if [ -e /etc/service/vsftpd ]
			then
				USED=`cat /etc/service/vsftpd`
				if [ $USED = 'disabled' ]
				then
					"$0" stop
				fi
			fi
		fi	
		;;

	stop) 
		pkill vsftpd
		;;

	restart)
		"$0" stop
		"$0" start
		;;

	status)
		if pidof vsftpd | sed "s/$$\$//" | grep -q [0-9] 
		then
			echo "running"
		else
			echo "stopped"
		fi
		;;

	*)
		echo $"Usage: $0 {start|stop|restart|reload}"
		;;
esac
