#!/bin/sh

case "$1" in
    start)
		if ! pidof pppd | sed "s/$$\$//" | grep -q [0-9] ; then
			if [ -e /etc/service/pppd ]
			then
				USED=`cat /etc/service/pppd`
				if [ $USED = 'enabled' ]
				then
					pppd file /etc/ppp/scripts/uc864-e >& /var/log/pppd &
				fi
			fi
		fi
		;;

	stop)
		pkill pppd 2>/dev/null
		;;

	restart)
		"$0" stop
		
		while pidof pppd | sed "s/$$\$//" | grep -q [0-9] 
		do
			sleep 1
		done
		sleep 1

		"$0" start

		;;

	status)
		if pidof pppd | sed "s/$$\$//" | grep -q [0-9] ; then
			echo "running"
		else
			echo "stopped"
		fi
		;;

	*)
		echo $"Usage: $0 {start|stop|restart|status}"
		exit 1
esac        
